version: '3'

volumes:
  pgdata:

services:
  web:
    container_name: ${CONTAINER_NAME}_nginx
    build: .docker/nginx
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - .:/var/www/html
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - php
  php:
    container_name: ${CONTAINER_NAME}_php
    build:
      context: ./.docker/php
      args:
        - TIMEZONE=${TIMEZONE}
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - .:/var/www/html
  db:
    container_name: ${CONTAINER_NAME}_postgres
    image: postgres:${POSTGRES_VERSION}
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5433:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./.docker/pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
