version: '3'

volumes:
  pgdata1:
  pgdata2:
  pgdata3:

networks:
  sak-network:
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
  default:

services:
  web:
    container_name: ${CONTAINER_NAME}_nginx
    build: .docker/nginx
    networks:
      - sak-network
      - default
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - .:/var/www/html
    ports:
      - 8081:80
    restart: unless-stopped
    depends_on:
      - php
  php:
    container_name: ${CONTAINER_NAME}_php
    build:
      context: ./.docker/php
      args:
        - TIMEZONE=${TIMEZONE}
    networks:
      - sak-network
      - default
    restart: unless-stopped
    depends_on:
      - db_m
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - .:/var/www/html
  db_m:
    container_name: db_m
    image: postgres:${POSTGRES_VERSION}
    networks:
      - sak-network
      - default
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - pgdata1:/var/lib/postgresql/data
      - ./.docker/pgsql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.docker/pgsql/master/postgresql.conf:/tmp/postgresql.conf
      - ./.docker/pgsql/master/pg_hba.conf:/tmp/pg_hba.conf
  db_s1:
    container_name: db_s1
    image: postgres:${POSTGRES_VERSION}
    depends_on:
      - db_m
    networks:
      - sak-network
      - default
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata2:/var/lib/postgresql/data
  db_s2:
    container_name: db_s2
    image: postgres:${POSTGRES_VERSION}
    depends_on:
      - db_m
    networks:
      - sak-network
      - default
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata3:/var/lib/postgresql/data
