SELECT 'CREATE DATABASE "${DB_DATABASE}"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_DATABASE}')\gexec
CREATE ROLE replication_user WITH LOGIN PASSWORD 'password' REPLICATION;
GRANT CONNECT ON DATABASE ${DB_DATABASE} TO replication_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO replication_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO replication_user;
GRANT USAGE ON SCHEMA public TO replication_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO replication_user;
